In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import pickle
input = open('data_class.pkl', 'rb')
obj = pickle.load(input)
input.close()
X_train = obj["X_train"]
X_test = obj["X_test"]
y_train = obj["y_train"]
y_test = obj["y_test"]

In [3]:
from sklearn.svm import SVC
svm = SVC(kernel = 'rbf', random_state = 10).fit(X_train, y_train)

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method

In [4]:
y_pred = svm.predict(X_test)
svm.score(X_test,y_test)

0.869413407821229

In [5]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[551 137]
 [ 50 694]]


In [6]:
svm = SVC(kernel = 'linear', random_state = 10).fit(X_train, y_train)

In [7]:
y_pred = svm.predict(X_test)
svm.score(X_test,y_test)

0.869413407821229

In [8]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[565 123]
 [ 64 680]]


In [9]:
svm = SVC(kernel = 'poly', random_state = 10).fit(X_train, y_train)

In [10]:
y_pred = svm.predict(X_test)
svm.score(X_test,y_test)

0.8652234636871509

In [11]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[534 154]
 [ 39 705]]


In [12]:
svm = SVC(kernel = 'sigmoid', random_state = 10).fit(X_train, y_train)

In [13]:
y_pred = svm.predict(X_test)
svm.score(X_test,y_test)

0.7967877094972067

In [14]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[538 150]
 [141 603]]


Модель на основе сигмоидального ядра имееет самое высокое значение точности, но классификация хуже всего распознает объекты. Таким образом наилучшей моделью является модель на основе линейного опорного вектора. Её результаты - это 187 неверно распознаных объектов. Коэффициент детерминации такой же, как и у логистической модели.